### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by Y0dler**
Move sections from the paper manuscript to the documentation due to word count restrictions.

### CODE REVIEW

**Comment by Y0dler** [comment]
Oh, it looks like the LaTeX formulae are not rendered correctly when you check the build of the documentation...

**Comment by Y0dler** [comment]
According to [this](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.imgmath), it should work natively already

**Comment by michaelosthege** [comment]
@Y0dler I fixed the formula formatting and applied a bunch of different MyST features such as cross references.

Navigation through the docs became a bit of a roller coaster, so IMO we should follow-up with adding a some sectioning to the navigation pane.

But this PR is ready from my side 👍

**Review by michaelosthege — APPROVED** [review]

**Comment by Y0dler** [comment]
Thanks a bunch for all the additions to documentation index!  
Sectioning as a follow-up sounds good and we should also change the content on the GitHub landing page (and include a more prominent link to the documentation).

**Pull request merged**
